site_name:           Lexicon.jl
repo_url:            https://github.com/peter1000/Lexicon.jl
site_description:    Julia package documentation generator.
site_author:         peter1000
theme:               flatly
markdown_extensions: [tables, fenced_code]
pages:
    - ['index.md', 'Introduction']
    - ['manual.md', 'Manual', 'Overview']
    - ['api/Lexicon.md', 'API', 'Lexicon']
    - ['api/index.md', 'API', 'Index']
